import React from 'react';
import { Container, Header} from 'semantic-ui-react'

export default props => {
  return (
    <Container text>
      <Header as='h2'>Seller Terms and Conditions</Header>
  
      <div itemprop="text">
      <ol>
      <li><strong>INTRODUCTION: </strong>These terms and conditions (the <strong>Site Terms</strong>) set out how you may use our services to sell your merchandise (<strong>Products</strong>) via thecom Marketplace, or the relevant part of the Marketplace (<strong>Site</strong>). In order to use the Site or any of our services (<strong>Our Services</strong>) to sell Products, you must create a valid Seller account for each <strong>Elected Country</strong> (being one of the United Arab Emirates, the Kingdom of Saudi Arabia, or Egypt) in which you wish to sell your Products. Our Services may be amended from time to time by us.</li>
      </ol>
      <ol start="2">
      <li><strong>WORDS USED IN THESE SITE TERMS: </strong>Capitalized terms or terms in bold have the meanings given to them in these Site Terms. <strong>Seller</strong>, shall mean either <strong>you</strong>, as an individual if using the services on behalf of yourself, or the business employing you as its representative (if registering for or using a service as (or part of) a business or any of your Affiliates (individually (in respect of each Elected Country) or collectively as the context requires)) who elects to create a Seller account in each Elected Country and/or register on the Site. The Seller agrees to be bound by and comply with these Site Terms.</li>
      </ol>
      <p>In these Site Terms, the words <strong>Vendlor,</strong> <strong>we </strong>or <strong>us </strong>or <strong>our</strong> means, as applicable, each of or all of the Vendlor Contracting Party(ies) (as set out for each Elected Country referred to below) or any of its Affiliates. The term &#x201C;<strong>Affiliate</strong>&#x201D; means, with respect to any entity, any other entity or Person that directly or indirectly controls, is controlled by, or is under common control with that entity. A &#x201C;<strong>Person</strong>&#x201D; means any individual, corporation, partnership, limited liability company, governmental authority, association, joint venture, division, or other cognizable entity, whether or not having distinct legal existence.</p>
      <ol start="3">
      <li><strong>CREATING A</strong><strong> SELLER ACCOUNT FOR AN ELECTED COUNTRY: </strong>In accordance with the directions on the Site, you will need to create a Seller account with us for each Elected Country in which you wish to receive Our Services. If you are in individual you need to be a resident of that Elected Country and if you are a business, you need to be able to conduct business in that Elected Country in accordance with the laws in that Elected Country. We may assist you with creation of a Seller account in each Elected Country after receiving necessary information from you (and each of your Affiliates if applicable). You must first familiarise yourself with the process set out on the Site and all the Site Terms. You must not register under a false name and/or impersonate any other Sellers&#x2019; log-in credentials, or password(s). Such fraudulent conduct could result in violation of applicable federal, national, regional or international laws and regulations (<strong>Applicable Laws</strong>) in the relevant Elected Country. You agree to provide all relevant information to us while your account is active. When registering your Seller account, for each Elected Country, you must provide valid and authentic supporting documents as we may specify (in accordance with Applicable Laws in the Elected Country) and/or as may be requested by us through the Site or your Seller account.</li>
      </ol>
      <ol start="4">
      <li><strong>PASSWORDS: </strong>If you choose, or you are provided with, a user name, password or any other piece of information as part of our security procedures, you must treat such information as confidential. You are solely responsible for maintaining the security of your password. You may not disclose your password to any third party (other than third parties authorized by you to use your account in accordance with these Site Terms) and you are solely responsible for any use of or action taken under your password. If your password is compromised, you must immediately change your password. We have the right to disable any user identification name or password, whether chosen by you or allocated by us, at any time, if in our reasonable opinion you have failed to comply with any of these Site Terms.</li>
      </ol>
      <ol start="5">
      <li><strong>SPECIFIC POLICIES:</strong> By creating a valid Seller account for each Elected Country, you agree, at the time of creation or registration, to be bound by and comply with these Site Terms, and all policies, protocols guidelines, and other terms incorporated on the Site (which shall form a part of these Site Terms). This shall include:</li>
      </ol>
      <ol>
      <li>any country specific terms about which you may be notified from time to time and that shall apply to each Elected Country for which you register or elect to use Our Services (using functionality we may enable for your Seller account); and</li>
      <li>any service specific terms for any of Our Services that you may request from us and which we may agree to provide to you from time to time (using functionality we may enable for your account) in accordance with such service specific terms (which may relate only to specific Products) (<strong>Other Service Terms</strong>) and which form part of these Site Terms. The Other Service Terms include, without limitation, the Fulfilled-by-Vendlor (<strong>FBS</strong>) Terms (<strong>FBS Terms</strong>) which are set out at the end of these Site Terms.</li>
      </ol>
      <ol start="6">
      <li><strong>Vendlor </strong><strong>CONTRACTING PARTY: </strong>If the Elected Country is:
      <ul>
      <li>the <strong>United Arab Emirates</strong>: the Vendlor Contracting Party is:
      <ul>
      <li>for Our Services referred to in these Site Terms (excluding the Other Service Terms), <strong>Vendlor</strong><strong>.Com FZ LLC</strong>, a limited liability company incorporated under the laws of the United Arab Emirates and registered at the Dubai Technology and Media Free Zone Authority with commercial register number 17646 whose main office is at Ibn Battuta Gate Tower, 601, Dubai, United Arab Emirates (<strong>Vendlor UAE MP</strong>); and</li>
      <li>for the FBS Services, <strong>Q-tech General Trading LLC</strong>, a limited liability company incorporated under the laws of the United Arab Emirates with commercial licence number 666871 whose registered office is at Dubai Investment Park, PO Box 54107 Dubai, United Arab Emirates (<strong>Vendlor UAE FBS</strong>), and together Vendlor UAE MP and Vendlor UAE FBS shall be referred to as &#x201C;<strong>Vendlor UAE</strong>&#x201D;;</li>
      </ul>
      </li>
      <li>the <strong>Kingdom of Saudi Arabia</strong>: the Vendlor Contracting Party is <strong>Afaq Q Tech General Trading LLC</strong>, a limited liability company incorporated under the laws of the Kingdom of Saudi Arabia with commercial registration number 1010434700 whose registered office is at Al Suleimaniyah Commercial Centre, Al Suleimaniyah District, Riyadh, Kingdom of Saudi Arabia (<strong>Vendlor KSA</strong>); and/or</li>
      <li><strong>Egypt</strong>: the Vendlor Contracting Party is <strong>Vendlor.Com for E-Commerce LLC</strong>, a limited liability company incorporated under the laws of Egypt with commercial registration number 45178 whose registered office is at 24 Ahmed Kamel St, Maadi Park, Building #3, New Maadi, Cairo, Egypt (<strong>Vendlor Egypt</strong>).</li>
      </ul>
      </li>
      </ol>
      <ol start="7">
      <li><strong>OUR MP SERVICES: </strong>According to these Site Terms, we offer web and mobile sites for you to offer Products (as selected by you and agreed with us) to customers, and complete transactions in each Elected Country as selected by you and agreed with us including as described at <a href="https://sell.Vendlor.com/sell">https://sell.Vendlor.com/sell</a> (<strong>Our MP Services, </strong>which are a part of Our Services). Save as otherwise set out in these Site Terms, the Seller acknowledges that Vendlor does not take title or ownership of the Products or the inventory of Products at any point in time by virtue of the provision of Our Services according to these Site Terms. Title to the Products shall remain with the Seller until successful and completed delivery to its customer, or upon return to the Seller.</li>
      </ol>
      <ol start="8">
      <li><strong>SELLER&#x2019;S</strong> <strong>DUTIES:</strong> You may only use the Site for lawful purposes and in a lawful manner. You must comply with all Applicable Laws in the Elected Country and you acknowledge that these may vary between different Elected Countries. You will be required to comply with any such differences as applicable. You must ensure that your Products correspond to the images uploaded to the Site and information supplied to us. It is your duty not to place any misleading advertisement or information about your Products or a brand on the Site. If you are found to be in breach of these Site Terms, you must accept return of Products and you may become liable to us under these Site Terms.</li>
      </ol>
      <p>Products that we consider are potentially harmful (including, for example, to the health and safety of individuals) may require you to provide additional warranties to us to continue to allow their sale via the Site. Specific Applicable Laws in the Elected Country may apply to the sale of such Products and it is your responsibility to adhere to such laws. Liabilities incurred for not following relevant health and safety requirements and/or selling Products which are harmful to individuals or any Persons property will be at your sole risk and cost. We reserve the right to reject Products that fall under our <u>prohibited item list</u>, as amended from time to time. Products offered for sale on the Site must comply with all laws and regulations and with Vendlor&#x2019;s policies and protocols as may be specified on the Site and updated from time to time. The sale of illegal, unsafe, or other restricted products listed on these pages, including products available only by prescription, is strictly prohibited. Prior to listing or requesting us to list the Products on the Site, you should carefully review the relevant guidance pages available on the Site. The examples provided in Help pages are not all-inclusive and are provided solely as an informational guide. We encourage you to seek independent legal advice if you have questions about the laws and regulations concerning your Products.</p>
      <ol start="9">
      <li><strong>SALE</strong><strong> AND FULFILMENT:</strong> Other than where we agree to provide Our Services to you in accordance with Other Service Terms (and then only in accordance with and to the extent set out in such Other Service Terms), for any of Our Services that you apply to use or use (and which we agree to provide), in each Elected Country, you will:
      <ul>
      <li>ensure that your Products do not cause any personal injury or damage to property;</li>
      <li>provide to Vendlor (on request) an updated copy of your trade license (if you are a corporate Person) or a copy of your passport or national ID (if you are a natural Person);</li>
      <li>provide the required warranties and maintenance for the purchased Products in accordance with market practices, Vendlor guidelines and protocols, and Applicable Law(s);</li>
      <li>remain responsible for after-sales services, guarantees, warranties, maintenance, and any defects that may arise for or in respect of your Products including where required in accordance with Applicable Law (which you may ask us to provide on your behalf);</li>
      <li>source, offer, sell and fulfil your Products, in each case in accordance with the terms of the applicable order and shipping information (with respect to any of your Products ordered through the Site), these Site Terms, and all terms provided by you (with our agreement) or us and displayed on the Site at the time of the order and be solely responsible for and bear all risk for those activities&#x37E;</li>
      <li>fulfil your Products using one of our authorised third party courier companies (which shall be notified to you using the details provided through your Seller account);</li>
      <li>package each of your Products in a commercially reasonable manner complying with all applicable packaging and labelling requirements as provided in each Elected Country(ies);</li>
      <li>subject to the Other Services Terms, at your own expense or your customer&#x2019;s expense (as agreed with us) ship each of your Products on or before either: (i) the end of the shipping availability period (which begins as of the date on which the relevant order is placed by the customer), or the shipping availability date, as applicable, specified by you in the relevant inventory/product data feed for your Product&#x37E; or (ii) if you do not specify shipping availability information in such inventory/product data feed or that your Product is in a product category that Vendlor designates as requiring shipment within, three business days after the date on which the relevant order is placed by the customer and you acknowledge and agree that we reserve the right to charge for any loss suffered or incurred by us for: (i) your delays in delivery against agreed timelines; or (ii) cancellation of a confirmed order placed by a custome<strong>r</strong>&#x37E;</li>
      <li>retrieve the order information and shipping information with respect to any of your Products ordered through the Site in order to comply with your obligations according to these Site Terms&#x37E;</li>
      <li>only cancel any sale of your Product(s) through the Site as permitted pursuant to guideline and policies issued by us and in force at the time of the applicable order or as may be required under these Site Terms&#x37E;</li>
      <li>fulfil your Products throughout the whole of the Elected Country(ies) (except to the extent prohibited by Applicable Law or these Site Terms)&#x37E;</li>
      <li>provide to Vendlor information regarding fulfilment and order status and tracking (to the extent available), in each case as requested by us using the processes designated by us, of which we may make any of this information publicly available&#x37E;</li>
      <li>comply with all instructions, if any, specified by the manufacturer, distributor, and/or licensor of a Product specifying the date before which specified information for such Product (e.g., title of a book) should not be disclosed publicly, or such Product should not be delivered or otherwise made available to customers&#x37E;</li>
      <li>be the Seller of each of your Products and not act on behalf of any other Person (in any capacity)&#x37E;</li>
      <li>include an order-specific packing slip, and, if applicable, any tax invoices, within each shipment of your Products&#x37E;</li>
      <li>identify yourself as the Seller of each of your Products on all packing slips or other information included or provided in connection with your Products and as the Person to which a customer may return the applicable product&#x37E; and</li>
      <li>except as expressly permitted by these Site Terms, not contact customers (whether by telephone, email or other communication method) confirming orders or fulfilment of your Products or for any other reason.</li>
      </ul>
      </li>
      </ol>
      <ol start="10">
      <li><strong>OUR POLICIES: </strong>The Site Terms are applicable to all activities or transactions made on or via the Site in each Elected Country. If Vendlor is notified by a Seller or a third party brand owner, or via a court, administrative or government order that Products or any part thereof violates, in accordance with Applicable Laws in the Elected Country, the <strong>Intellectual Property Rights (IPR</strong>s) (which means without limitation (i) copyright, patents, database rights and rights in trademarks, designs, know-how domain&#xA0;name,&#xA0;moral&#xA0;right,&#xA0;trade&#xA0;secret&#xA0;right,&#xA0;or&#xA0;any other&#xA0;intellectual&#xA0;property&#xA0;right&#xA0;arising&#xA0;under&#xA0;any Applicable&#xA0;Laws and&#xA0;all ancillary&#xA0;and&#xA0;related&#xA0;rights and confidential information (whether registered or unregistered); (ii) applications for registration, and the right to apply for registration, for any of these rights; and (iii) all other IPRs and equivalent or similar forms of protection existing anywhere in the world and&#xA0;causes&#xA0;of&#xA0;action&#xA0;for&#xA0;violation,&#xA0;misappropriation&#xA0;or infringement&#xA0;of&#xA0;any&#xA0;of&#xA0;the&#xA0;foregoing) of any third party or any other rights of any third party or any Applicable Laws in the Elected Country, we may remove such Products from the Site and our warehouses (if relevant) at our sole discretion or request removal of such Products by the Seller within a reasonable timeframe notified in writing or through the Seller account. Seller acknowledges that Vendlor may from time to time introduce and implement new business rules, and customer care guidelines. Additionally, we are under no obligation to provide any information, material or document back to you, either before or after termination of these Site Terms or cancelation of a Seller account.</li>
      </ol>
      <ol start="11">
      <li><strong>FEES AND PAYMENTS:</strong> Except as provided otherwise, our fees for Our Services are set out on the Site <a href="http://uae.Vendlor.com/ae-en/selling-fees/c/">http://uae.Vendlor.com/ae-en/selling-fees/c/</a> or as illustrated through the Seller&#x2019;s account for each Elected Country, as may be updated from time to time. Seller is responsible for payment of taxes in connection with Products (including withholding costs and any interest or penalty payments that may be imposed by any competent authority for late or non-payment of such taxes, in each case in accordance with any Applicable Laws in the Elected Country). All such amounts are in addition to our fees. You authorize us (and will provide us documentation evidencing your authorization upon our request) to verify your information (including any updated information), to obtain credit reports about you from time to time, where agreed with you in each case, to obtain credit authorizations from the issuer of your credit card, and to charge your credit card or debit your bank account for any sums payable by you to us (in reimbursement or otherwise). Except as provided otherwise, all amounts contemplated by these Site Terms will be expressed and displayed in the currency set out on the Site or referenced through the Seller&#x2019;s account for each Elected Country, and all payments contemplated by these Site Terms will be made currency set out on the Site or referenced through the Seller&#x2019;s account for each Elected Country.</li>
      </ol>
      <p>All fees payable by Seller under these Site Terms are exclusive of applicable taxes and duties, including, without limitation VAT, sales and similar transaction taxes, excise taxes and gross receipts taxes (&#x201C;<strong>Indirect Taxes</strong>&#x201D;). If the fees payable by Seller are subject to Indirect Taxes, then the Indirect Taxes will be charged by Vendlor in addition to the fees payable under these Site Terms. Seller will provide such information to Vendlor as reasonably required to determine whether Vendlor is obligated to collect Indirect Taxes from Seller or to allow Vendlor to comply with its legal obligations in relation to the correct collection and enforcement of Indirect Taxes. Shipment charges incurred by Vendlor in relation to Seller or a customer if any will be deducted by Vendlor before releasing payment during the relevant month. We will use reasonable endeavours to ensure that the cost of each item minus our fee as set out on the Site will be released to Seller&#x2019;s account on the Site in accordance with the relevant payment terms set out on the Sites in the relevant Elected Country after successful Product delivery, and in any event not later than thirty days after delivery. This period will always be subject to any customer dispute or dispute resolution time. Thereafter, Sellers can transfer such balance to his/her bank account at any time. Our obligation to remit funds received by us on your behalf is limited to funds that we have actually received less amounts owed to us, subject to chargeback or reversal or amounts withheld for anticipated claims in accordance with these Site Terms. The parties shall endeavour to resolve all and any payment conflicts amicably, and in the absence of an acceptable resolution, the parties will refer the conflict in accordance with clause</p>
      <p>Notwithstanding any other provision of these Site Terms and without prejudice to Vendlor&#x2019;s other rights and remedies, Seller indemnifies Vendlor for all loss (including to the extent that any loss is direct or indirect and/or relates to or includes any costs of investigation or professional fees or expenses) incurred or suffered (a) if the Seller&#x2019;s Product is found counterfeit or refurbished or not to be original; or (b) any other type of fraudulent conduct is identified on the part of Seller.</p>
      <ol start="12">
      <li><strong>SELLER WARRANTIES AND REPRESENTATIONS</strong><strong>: </strong>Seller represents and warrants that: (i) if you are a business, you are duly organized, validly existing and in good standing under the Applicable Laws of the Elected Country in which your Seller account is registered and that you are registering for Our Services provided under these Site Terms within such Elected Country; (ii) Seller has all requisite right power, and authority to enter into these Site Terms, perform your obligations, and grant the rights, licenses, and authorizations in these Site Terms &#x37E; (iii) Seller has the power and licences, permissions, authorisations, proprietary rights, consents and permits in the Products and to sell and promote Products in the territory in which they are sold via the Site; (ii) Seller&#x2019;s Products conform to applicable quality and safety standards; (iv) Seller shall be solely responsible for any Products placed or distributed through the Site and breach of any third party contracts; (v) placement and sale of Seller&#x2019;s Products through the Site will not be in breach of any Applicable Laws in the Elected Country or third party rights; (vi) all Products including the Materials supplied to Vendlor are original and free from any defects; (vi)&#xA0;Seller will not engage in any unfair trade practices, and/or publish any inaccurate or misleading advertisement or information about Products on or via the Site, (viii) Seller will neither sell nor deliver to a customer any refurbished or used items, and the Products will always be new and unused; and (ix) Seller understands its consumer protection obligations as a supplier and indemnifies Vendlor against any losses or costs incurred by Vendlor in respect of Seller&#x2019;s obligations under any Applicable Laws in the Elected Country.</li>
      </ol>
      <ol start="13">
      <li><strong>RETURNS: </strong>Seller undertakes to comply with our return and refund policy as referred to on the Site at <a href="https://uae.Vendlor.com/ae-en/return-policy/c/">https://uae.Vendlor.com/ae-en/return-policy/c/</a>, at its sole cost, whereby Products sold on the Site are subject to a return and refund in the applicable return and refund period starting from the date of delivery of the Products to the customer. The return policy shall apply as long as the Products are in the original packaging and are returned to the Seller in the original condition in which they were purchased and received. In accordance with the policy, our customer support team will arrange return to Seller by arranging a courier pick-up and return to the Seller, at which point, a full refund will be made by Seller to the relevant customer. Subject to the provisions of this clause, Seller must always accept return of a Product. In the event of a return which is not based on any alleged breach of Seller&#x2019;s obligations, Vendlor will not levy any costs or penalty (unless expressly stated otherwise in these Site Terms). We shall return the Products to your designated shipping address. If (to the extent that we are arranging the return) (a) the designated shipping address we have for you is out-dated or incorrect, (b) you have not provided a designated shipping address in the Elected Country, or (c) we cannot make arrangements for you to pay for the return shipment, then the Product(s) will be deemed abandoned and we, to the extent permitted by Applicable Laws in the Elected Country, may elect to dispose of them. You will reimburse us for all costs and expenses we incur in connection with the storage, and return or disposal of any Products. We, if we so elect, may dispose of any Products (and you will be deemed to have consented to our action) immediately if we determine in our sole discretion that such Products create a safety, health, or liability risk to Vendlor, our personnel, or any third party. To the extent that we elect to dispose of any such Products, title to each such disposed Product(s) will transfer to us at no cost, as necessary for us to dispose of the Product(s), and we will retain all proceeds, if any, received from the disposal.</li>
      </ol>
      <p>Except for any of your Products fulfilled according to Other Service Terms, you will promptly accept and process cancellations, returns, refunds, and adjustments in accordance with the return and refund policies published on the Site and applicable to Products and Our Services offered via the Site, using functionality we enable for your account. Without limiting your obligations, we may in our sole discretion accept, calculate, and process cancellations, returns, refunds, and adjustments for the benefit of customers. You will route any payments to customers in connection with any sale of your Product(s) through the relevant Vendlor Contracting Party via the Site. We will make any payments to customers in the manner we determine, and you will reimburse us for any amounts we pay (or we may deduct such amounts through your Seller account).</p>
      <ol start="14">
      <li><strong>DELIVERY ERRORS AND NON-CONFORMITIES:</strong> You are solely responsible for any non-performance, non-delivery, mis-delivery, theft, or other mistake or act in connection with the fulfilment of your Products, except to the extent caused by: (a) credit card fraud (and where we are responsible for such fraud)&#x37E; or (b) our failure to make available to you (with respect to any of your Products ordered through the Site), the order information and shipping information as it was received by us or resulting from address verification. Notwithstanding the previous sentence, for those of your Products that are fulfilled according to the FBS Terms, if any, the FBS Terms for the Site will apply to non-delivery, mis-delivery, theft, or other mistake or act in connection with the fulfilment of those Products. You are responsible for any nonconformity or defect in, or any public or private recall of, any of your Products or other products provided in connection with your Products. You will notify us promptly as soon as you have knowledge of any public or private recalls of your Products or other products provided in connection with your Products.</li>
      </ol>
      <ol start="15">
      <li><strong>INTELLECTUAL PROPERTY:</strong> Vendlor has the right to and you license Vendlor to use, copy, distribute, modify and disclose to third parties any content, trademarks, materials or product images that you upload on the Site (and Seller warrants that it is entitled to grant that licence). This license you grant to us is royalty-free, nonexclusive, worldwide, perpetual, irrevocable right and license to use, reproduce, perform, display, distribute, adapt, modify, reformat, create derivative works of, and otherwise commercially or non-commercially exploit in any manner, any and all of Seller&#x2019;s Materials, and to sublicense these rights to the Affiliates of Vendlor&#x37E; provided, however, that we will not alter any of Seller&#x2019;s trademarks from the form provided by Seller (except to resize trademarks to the extent necessary for presentation, so long as the relative proportions of such trademarks remain the same) and will comply with Seller&#x2019;s removal requests as to specific uses of Seller&#x2019;s trademarks (provided you are unable to do so using standard functionality made available to you via the Site or Our Service (as applicable)). Nothing in these Site Terms will prevent or impair Vendlor&#x2019;s right to use Seller&#x2019;s Materials without your consent to the extent that such use is allowable without a license from Seller or its Affiliates under Applicable Law. We do not grant any license to you except solely as is strictly necessary for you to use Our Services that we agree to provide to you. &#x201C;<strong>Materials</strong>&#x201D; means all technology, trademarks, content, product information, data, materials, and other items or information provided or made available by you or your Affiliates to Vendlor or its Affiliates.</li>
      </ol>
      <ol start="16">
      <li><strong>CHANGES, UPDATES AND UPGRADES:</strong> Vendlor reserves the right to change these Site Terms at any time and in its sole discretion. Any changes will be effective upon the earlier of: posting of the revisions on the Site and/or notification to you (including by email, or through your Seller account), without any further notice to you. You are responsible for reviewing any applicable changes. Your continued use of the Site (which may be illustrated through your accessing of your Seller account) and Our Services following our posting of any changes, notification and/or &#x2018;click through&#x2019; acceptance will constitute your acceptance of such changes. If you do not agree to any change to these Site Terms, you must not continue to use the Site or Our Services. The Seller agrees that no terms of business that it produces or sends to Vendlor shall have any legal force or effect. Whilst Vendlor endeavours to keep the Site safe and secure, we cannot guarantee the continuous operation or access to the Site. Seller acknowledges that Vendlor may, from time to time, upgrade features of the Site and or certain aspects of Our Services that it provides to its customers generally. In order for Seller to benefit from any such upgrade, Vendlor may make changes to the provision of any of Our Services and the procedures by which Seller receives any of Our Services. Vendlor may also, from time to time change any of Our Services to the extent required to comply with any change in Applicable Laws in the Elected Country.</li>
      </ol>
      <ol start="17">
      <li><strong>Vendlor&#x2019;S LIABILITY:</strong> The Site and any of Our Services provided through it, or any functionality used or relied on, including all content, software, functions, materials, and information made available on or provided in connection with Our Services, are provided &#x201C;as-is.&#x201D; Each Vendlor entity or Person is severally liable for its own obligations under these Site Terms and is not jointly liable for the obligations of any other Vendlor entity or Person under these Site Terms. As a user of the Site, Seller uses the Site and Our Services provided to Seller at its own risk. To the fullest extent permissible by law, Vendlor and its Affiliates disclaim: (i) any representations or warranties regarding these Site Terms, any of Our Services or the transactions contemplated by these Site Terms, including any implied warranties of merchantability, fitness for a particular purpose, or non-infringement&#x37E; (ii) implied warranties arising out of course of dealing, course of performance, or usage of trade&#x37E; and (iii) any obligation, liability, right, claim, or remedy in tort, whether or not arising from our negligence. Vendlor does not warrant that the functions contained in the Site and Our Services will meet Seller&#x2019;s requirements or be available, timely, secure, uninterrupted, or error free, and Vendlor will not be liable for any service interruptions, including but not limited to system failures or other interruptions that may affect the receipt, processing, acceptance, completion, or settlement of any transactions. Vendlor is not involved in transactions between customers and Sellers or other participant dealings, if a dispute arises between one or more participants, each participant releases Vendlor and its affiliates (and their agents and employees) from claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of or in any way connected with such disputes. Our liability arising out of or in connection with these Site Terms or the transactions contemplated, whether in contract, warranty, tort (including negligence, product liability, or other theory) to Seller or any other Person for cost of cover, recovery or recoupment of any investment made by Seller or its Affiliates in connection with these Site Terms, or for any loss of profit, revenue, business or data or punitive or consequential damages arising out of or relating to these Site Terms, even if Vendlor or its Affiliates have been advised of the possibility of those costs or damage, shall not exceed in aggregate an amount equal to the amounts during the prior six-month period paid to Seller in connection with the particular service giving rise to the claim immediately preceding the event giving rise to the liability.</li>
      </ol>
      <ol start="18">
      <li><strong>SELLER&#x2019;S RELEASE AND INDEMNITY:</strong> Seller releases Vendlor and agrees to indemnify, defend, and hold harmless Vendlor, its Affiliates, and its respective officers, directors, employees, representatives, and agents against any claim, loss, damage, settlement, cost, expense, or other liability (including, without limitation, attorneys&#x2019; fees) (each, a &#x201C;<strong>Claim</strong>&#x201C;) arising from or related to: (a) Seller&#x2019;s actual or alleged breach of any obligations in these Site Terms&#x37E; (b) any of Seller&#x2019;s other means through which it or any of its Affiliates offers products or services, other than the Site, (b) your Products (including their offer, sale, performance, and fulfilment), (c) your Materials, (d) any actual or alleged infringement of any Intellectual Property Rights by any of the foregoing, and any personal injury, death, or property damage related thereto&#x37E; (e) any third party warranting, administering or otherwise involved in the offer, sale, performance, or fulfilment of your Products, including any of your employees, representatives, agents, contractors, or subcontractors (including any act or omission by any of them or any Claim brought or directed by any of them)&#x37E; or (d) taxes imposed on or payable by Seller or for the sale and/or supply of Products. Seller will use counsel reasonably satisfactory to Vendlor to defend each indemnified Claim. If at any time Vendlor reasonably determines that any indemnified Claim might adversely affect Vendlor, we may take control of the defence. You may not consent to the entry of any judgment or enter into any settlement of a Claim without our prior written consent, which may not be unreasonably withheld. We reserve the right to enforce our rights under this provision by withholding amounts otherwise due to Seller under these Site Terms.</li>
      </ol>
      <ol start="19">
      <li><strong>MITIGATION OF LOSS: </strong>Except in relation to any Claim or action for non-payment of the fees, each party shall take all reasonable steps to mitigate the loss and damage it incurs in relation to any Claim or action (whether for negligence, breach of contract, misrepresentation, under any indemnity or otherwise) which it brings against the other.</li>
      </ol>
      <ol start="20">
      <li><strong>INSURANCE </strong>If the gross proceeds from any sale of your Product(s) through the Site exceeds an amount equivalent to U.S. Dollars ten thousand (USD10,000 or the equivalent amount in the local currency of the relevant Elected Country) during each month over any period of three (3) consecutive months, or otherwise if requested by us, then within thirty (30) days thereafter, you will maintain at your expense throughout the remainder of the Term for each applicable Elected Country commercial general, umbrella or excess liability insurance with an equivalent limit of one million U.S. Dollars (USD1,000,000) or the equivalent amount in the local currency of the relevant Elected Country per occurrence and in aggregate covering liabilities caused by or occurring in conjunction with the operation of your business, including Products, products/completed operations and bodily injury, with policy(ies) naming the relevant Vendlor Contracting Party and its assignees as additional insureds. At our request, you will provide to us certificates of insurance for the coverage.</li>
      </ol>
      <ol start="21">
      <li><strong>CONFIDENTIALITY:</strong> During the course of your use of Our Services, you may receive information relating to us or to Our Services, (including Vendlor Transaction Information) that is not known to the general public (&#x201C;<strong>Confidential Information</strong>&#x201C;). You agree that: (a) all Confidential Information will remain Vendlor&#x2019;s exclusive property&#x37E; (b) you will use Confidential Information only as is reasonably necessary for your participation in Our Services&#x37E; (c) you will not otherwise disclose Confidential Information to any other person or third party&#x37E; and (d) you will take all reasonable measures to protect the Confidential Information against any use or disclosure that is not expressly permitted in these Site Terms. You may not issue any press release or make any public statement related to Our Services, or use our name, trademarks, or logo, in any way (including in promotional material) without our advance written permission, or misrepresent or embellish the relationship between us in any way.</li>
      </ol>
      <ol start="22">
      <li><strong>DISCLOSURE OF INFORMATION: </strong>Vendlor reserves the right to report any activity that either it suspects violates any Applicable Law to appropriate law enforcement officials, regulators, or other third parties. In order to cooperate with governmental requests, to protect Vendlor and its customers, or to ensure the integrity and operation of Vendlor&#x2019;s business and systems, Vendlor may access and disclose any information it considers necessary or appropriate, including but not limited to Seller account details, contact details, IP address and traffic information, usage history, and posted content. Both Vendlor and Seller each shall protect customer data as per their respective policies and the Applicable Laws of the Elected Country.</li>
      </ol>
      <ol start="23">
      <li><strong>USE OF Vendlor TRANSACTION INFORMATION</strong> You will not, and will cause your Affiliates not to, directly or indirectly: (a) disclose any Vendlor Transaction Information (except that you may disclose that information solely as necessary for you to perform your obligations under these Site Terms if you ensure that every recipient uses the information only for that purpose and complies with the restrictions applicable to you related to that information)&#x37E; (b) use any Vendlor Transaction Information for any marketing or promotional purposes whatsoever, or otherwise in any way inconsistent with our or your privacy policies or Applicable Law in an Elected Country&#x37E; (c) contact a Person that has ordered Your Product with the intent to collect any amounts in connection therewith or to influence that Person to make an alternative transaction&#x37E; (d) disparage us, our Affiliates, or any of their or our respective products or services or any customer&#x37E; or (e) target communications of any kind on the basis of the intended recipient being a Site user. In addition, you may only use tools and methods that we designate to communicate with users of our Site regarding transactions that you carry out on it, including for the purpose of scheduling, communicating, or cancelling the fulfilment of Products. The terms of this paragraph do not prevent you from using other information that you acquire without reference to Vendlor Transaction Information for any purpose, even if that information is identical to Vendlor Transaction Information, provided that you do not target communications on the basis of the intended recipient being a Site user. <strong>Vendlor Transaction Information</strong> means, collectively, order information and any other data or information acquired by you or your Affiliates from Vendlor, its Affiliates, or otherwise as a result of these Site Terms, the transactions contemplated by these Site Terms, or the parties&#x2019; performance under these Site Terms.</li>
      </ol>
      <ol start="24">
      <li><strong>RIGHTS IN MWS, MWS MATERIALS, MWS SPECIFICATIONS, AND THE AMAZON NETWORK.</strong> Marketplace Web Service (&#x201C;<strong>MWS</strong>&#x201D;) is a Service that is operated by our Affiliate that enables your systems to interface with certain features or functionality available to Sellers. &#x201C;<strong>MWS Materials</strong>&#x201D; <em>means any software, data, text, audio, video, images, or other content we make available in connection with MWS, including application programming interfaces, related documentation, software libraries, and other supporting materials, regardless of format</em>. <strong>MWS Specifications</strong>&#x201D; <em>means any technical and operational specifications, security protocols and other documentation or policies provided or made available by us with respect to MWS or MWS Materials</em>. &#x201C;<strong>Amazon Network</strong>&#x201D; <em>means our Affiliates internal data centre facilities, servers, networking equipment, and host software systems (e.g., virtual firewalls) that are within our or their reasonable control and are used to provide MWS or MWS Materials</em>. As between you and us, we, our Affiliates or our licensors own all right, title, and interest in and to MWS, MWS Materials, MWS Specifications, and the Amazon Network. You obtain no rights under these Site Terms from us or our licensors to MWS, MWS Materials, MWS Specifications, or the Amazon Network, including any related intellectual property rights.</li>
      </ol>
      <ol start="25">
      <li><strong>TERM AND TERMINATION:</strong> These Site Terms shall commence on the date on which your account is created or a written contract is signed with us, and shall continue unless and until terminated by us or you. Vendlor may terminate these Site Terms (in full or in part, or in respect of any Elected Country) at any time at its sole discretion although Vendlor shall try to give fifteen days&#x2019; notice to Sellers. Upon termination, your Seller account shall cease to be accessible (either generally or in respect of a particular Elected Country). No termination of these Site Terms (howsoever occasioned) shall: (i) affect any accrued rights or liabilities of either party; (ii) affect the coming into force or the continuance in force of any provision of these Site Terms which is expressly or by implication intended to come into force or continue in force on or after termination; or (iii) require a court or judicial order. To the extent relevant, Seller shall immediately return to Vendlor all property (including without limitation, Confidential Information and all material related to any customers) that it has received from Vendlor in connection with the performance of its obligations.</li>
      </ol>
      <ol start="26">
      <li><strong>SUSPENSION OF SERVICES:</strong> Vendlor may suspend performance of Our Services or access to a Seller account (either generally or in respect of a particular Elected Country) without liability where we have identified an actual or potential personal, financial or legal risk to the customer (which may include the following circumstances: (i) if Seller breaches these Site Terms or any of our policies; (ii) if Seller fails to reasonably cooperate with an investigation by Vendlor; (iii) where Vendlor reasonably believes that its continued provision of any of Our Services would expose Seller or Vendlor or their respective affiliates or customers to a material security risk or a regulatory action; or (iv) Seller&#x2019;s performance does not meet Vendlor&#x2019;s reasonable projections).</li>
      </ol>
      <ol start="27">
      <li><strong>FORCE MAJEURE: </strong>We will not be liable for any delay or failure to perform any of our obligations under these Site Terms by reasons, events or other matters beyond our reasonable control.</li>
      </ol>
      <p><strong>&#xA0;</strong></p>
      <ol start="28">
      <li><strong>GOVERNING</strong><strong> LAW:</strong> These Site Terms shall be governed by and construed in accordance with:
      <ul>
      <li>the laws of the United Arab Emirates as applied in the Emirate of Dubai, if the Vendlor Contracting Party is Vendlor UAE;</li>
      <li>the laws of the Kingdom of Saudi Arabia, if the Vendlor Contracting Party is Vendlor KSA; or</li>
      <li>the laws of Egypt, if the Vendlor Contracting Party is Vendlor Egypt.</li>
      </ul>
      </li>
      </ol>
      <ol start="29">
      <li><strong>DISPUTES</strong>: Any dispute, claim or controversy arising out of or in connection with these Site Terms (including a dispute, claim or controversy relating to any non-contractual obligations arising out of or in connection with these Site Terms) shall be referred to the parties&#x2019; respective officers for resolution. If any dispute remains unresolved twenty one days after being referred to the parties&#x2019; officers, it shall be finally settled:
      <ul>
      <li>if the Vendlor Contracting Party is a Person forming part of Vendlor UAE: by arbitration under the Arbitration Rules of the DIFC-LCIA Arbitration Centre, which Rules are deemed to be incorporated by reference into this clause. The number of arbitrators shall be one. The seat, or legal place, of arbitration shall be Dubai International Finance Centre. The language to be used in the arbitration shall be English;</li>
      <li>if the Vendlor Contracting Party is Vendlor KSA: save as set out below, through the commercial courts of the Board of Grievances of the Kingdom of Saudi Arabia which shall have exclusive jurisdiction; or</li>
      <li>if the Vendlor Contracting Party is Vendlor Egypt: save as set out below, by arbitration under the Arbitration Rules of the DIFC-LCIA Arbitration Centre, which Rules are deemed to be incorporated by reference into this clause. The number of arbitrators shall be one. The seat, or legal place, of arbitration shall be Dubai International Finance Centre. The language to be used in the arbitration shall be English.</li>
      </ul>
      </li>
      </ol>
      <p>Notwithstanding the foregoing, Vendlor may seek injunctive relief in any court of competent jurisdiction in respect of any matter concerning the infringement of its intellectual property rights or the use of its Site to infringe any third party&#x2019;s intellectual property rights.</p>
      <ol start="30">
      <li><strong>INDEPENDENT PARTIES:</strong> You and the Vendlor Contracting Parties are independent contractors, and nothing in these Site Terms will create any partnership, joint venture, agency, franchise, sales representative, or employment relationship between us. You will have no authority to make or accept any offers or representations on our behalf. These Site Terms will not create an exclusive relationship between you and us. Nothing expressed or mentioned in or implied from these Site Terms is intended or will be construed to give to any Person other than the parties to these Site Terms any legal or equitable right, remedy, or claim under or in respect to these Site Terms. These Site Terms and all of the representations, warranties, covenants, conditions, and provisions in these Site Terms are intended to be and are for the sole and exclusive benefit of Vendlor, you, and customers. As between you and us, you will be solely responsible for all obligations associated with the use of any third party service or feature that you permit us to use on your behalf, including compliance with any applicable terms of use. You will not make any statement, whether on your site or otherwise, that would contradict anything in this clause.</li>
      </ol>
      <ol start="31">
      <li><strong>WAIVER: </strong>Vendlor&#x2019;s rights under these Site Terms: (i) may be exercised as often as necessary; (ii) unless otherwise expressly provided in these Site Terms, are cumulative and not exclusive of rights and remedies provided by Applicable Law; and (iii) may be waived only in writing and specifically. Delay in the exercise or non-exercise of any right is not a waiver of that right.</li>
      </ol>
      <ol start="32">
      <li><strong>THIRD PARTIES: </strong>Except in the case of Affiliates of Vendlor, a Person who is not a Party to these Site Terms may not enforce any of them.</li>
      </ol>
      <ol start="33">
      <li><strong>SEVERABILITY</strong>. If any of these Site Terms and the documents referred to in them (including any Other Service Terms) is or becomes illegal, invalid or unenforceable in any jurisdiction, such illegality, invalidity or unenforceability shall not affect: (i) the legality, validity or enforceability in that jurisdiction of any other term of these Site Terms and the documents referred to in them (including any Other Service Terms); or (ii) the legality, validity or enforceability in other jurisdictions of that or any other provision of these Site Terms and the documents referred to in them (including any Other Service Terms).</li>
      </ol>
      <ol start="34">
      <li><strong>ENTIRE AGREEMENT:</strong> These Site Terms and the documents referred to in them (including any Other Service Terms) contains the whole agreement between the parties relating to the contracts, agreements and transactions contemplated by them and supersedes all previous agreements between the parties relating to these contracts, agreements and transactions. Except as required by Applicable Law, no terms shall be implied (whether by custom, usage or otherwise) into these Site Terms and the documents referred to in them. Each party acknowledges that, in agreeing to enter into these Site Terms and the documents referred to in them (including any Other Service Terms) it has not relied on any express or implied representation, warranty, collateral contract or other assurance (except those set out in these Site Terms and the documents referred to in it).</li>
      </ol>
      <ol start="35">
      <li><strong>NOTICES</strong><strong>:</strong>All notices, demands, requests, approvals, consents or other communications to be given or delivered under these Site Terms (&#x201C;<strong>Notices</strong>&#x201C;) by you to Vendlor must be given to the relevant Vendlor Contracting Party, with a copy to each Vendlor UAE entity, in writing. Notice will be deemed to have been given when delivered by courier and signed for by a Vendlor employee three days after such signature to the addresses has been given on the Site. We may notify you in writing via your email account or by delivering a hard copy of such notice by courier to the address you have provided to us and which in each case will be deemed to have been given upon being sent or dispatched (as appropriate). If there is any conflict or inconsistency between the provisions of the English language version of these Site Terms and any translated version, the wording of the English language version shall prevail.</li>
      </ol>
      <ol start="36">
      <li><strong>COMPLIANCE:</strong>
      <ul>
      <li>Seller represents and warrants that the country of origin of the Products is not a country subject to US or other applicable government authority sanctions prohibiting a US Person or other individual, corporation, organization or entity from importing such Products at the time of import into the destination country or at the time Seller delivers the Products to Vendlor.&#xA0; Seller represents and warrants that all Products that Seller provides to Vendlor are not controlled under the US Export Administration Regulations (EAR), EU Dual-Use Regulations, US International Traffic in Arms Regulations (ITAR), or any other applicable government export laws and regulations, unless Seller discloses to Vendlor in advance of shipment or transfer in writing and provides to Vendlor complete, accurate and up to date information necessary or that Vendlor may otherwise request to lawfully export the Products to Seller (Export Information), including, but not limited to, the US, EU or other government authority export control classification number(s), any applicable Commodity Classification (CCATS) or classification ruling, any applicable commodity jurisdiction rulings, a copy of the export license (where an export license is required), country of origin, and, where applicable, the General License type or license exception eligibility.</li>
      <li>Seller represents and warrants that Seller and its financial institution(s) are not subject to sanctions or otherwise designated on any list of prohibited or restricted parties or owned or controlled by such a party, including but not limited to the lists maintained by the United Nations Security Council, the US Government (e.g., the US Department of Treasury&#x2019;s Specially Designated Nationals list and Foreign Sanctions Evaders list and the US Department of Commerce&#x2019;s Entity List), the European Union or its member states, or other applicable government authority.</li>
      <li>Notwithstanding anything to the contrary herein, nothing in the Site Terms shall, or shall be interpreted or construed to, induce or require either party hereto to act in any manner (including taking or failing to take any actions in connection with a transaction) which is inconsistent with or penalized under any U.S. laws, regulations, rules, or requirements that apply to any party to these Site Terms.</li>
      </ul>
      </li>
      </ol>
      <ol start="37">
      <li><strong>ASSIGNMENT: </strong>Neither party may assign its rights or obligations set out in these Site Terms without the prior written consent of the other party, except that Vendlor may assign these Site Terms to an Affiliate or in connection with any merger, reorganization, sale of all or substantially all of its assets or any similar transaction. Subject to this limitation, these Site Terms will be binding upon, inure to the benefit of, and be enforceable by the parties and their respective successors and assigns.</li>
      </ol>
      <p>Contact <a href="mailto:Legal@Vendlor.com">Legal@Vendlor.com</a> if you have any questions on these Site Terms.</p>
      <p><strong>FULFILLED BY Vendlor (FBS): FBS TERMS</strong><br/>
      <a href="http://www.Vendlor.com"><strong>www.Vendlor.com</strong></a></p>
      <ol>
      <li><strong>FBS SERVICES: </strong>Following the registration by the Seller of an account on the Site in order to sell Products via the Site in the relevant Elected Country, using functionality we may enable for your account, you shall become eligible to receive from Vendlor the &#x201C;direct-to-consumer&#x201D; order fulfillment services in the Elected Country. These services are generally described on the Site at<a href="/help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/"> http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a> which may be amended from time to time, and are called the &#x201C;<strong>FBS Services</strong>&#x201D;. As set out on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a>, the FBS Services are separated into Storage Services and Fulfillment Services (and are a sub-category of the Services provided according to the Site Terms).</li>
      </ol>
      <ol start="2">
      <li><strong>FBS TERMS: </strong>Upon agreeing to provide the FBS Services to you, in the Elected Country, (and to your Affiliates in each other Elected Country(ies) as agreed with us), we shall do so in accordance with these terms which are called the &#x201C;<strong>FBS Terms</strong>&#x201D;. These FBS Terms are part of the Site Terms, and, unless specifically provided otherwise, apply only to the Seller&#x2019;s participation in FBS and the receipt of the FBS Services in each selected Elected Country as agreed with us. By using the FBS Services or listing Products for FBS, you (either in your individual capacity or on behalf of the business that you represent) as the Seller, reconfirm your agreement to be bound by the Site Terms and the FBS Terms. The FBS Terms apply only to the FBS Services. Save as otherwise set out in these FBS Terms, the Seller acknowledges that we do not take title or ownership of the FBS Products or the inventory of FBS Products at any point in time by virtue of the provision of these FBS Services according to these FBS Terms. Title to the FBS Products shall remain with the Seller until successful and completed delivery to the customer, or will remain with Seller for FBS Products that are returned to the Seller. You expressly agree that the Vendlor may engage its Affiliate(s) or a third party in order to complete one or more of the FBS Services. To the extent of any inconsistency or conflict between the Site Terms and the FBS Terms, the FBS Terms, unless expressly stated otherwise, take precedence.</li>
      </ol>
      <ol start="3">
      <li><strong>ELECTED COUNTRIES: </strong>Unless expressly agreed otherwise with Vendlor, the FBS Services are limited to FBS Products (as defined in paragraph 5 below of these FBS Terms) that are shipped to and from fulfillment centers located within the applicable Elected Country, to be delivered to customers in the same Elected Country only, subject to the Cross Border FBS (as set out below). Neither Vendlor, nor any third party, shall supply or be required to supply any services falling outside the scope of the FBS Services.</li>
      </ol>
      <ol start="4">
      <li><strong>CROSS BORDER FBS SERVICES: </strong>To the extent that the Elected Country is United Arab Emirates, then Vendlor UAE FBS may offer the Fulfillment Services aspect of the FBS Services to the Seller outside of the Elected Country to any of the Kingdom of Saudi Arabia, Bahrain, Kuwait, Qatar and Oman and such other countries as Vendlor may determine from time to time (in each and every case, and at all times, strictly subject to Applicable Laws in the UAE or in any destination country) (<strong>Cross</strong> <strong>Border FBS</strong>). If you elect to participate in our &#x201C;<strong>Cross</strong> <strong>Border FBS</strong>&#x201D;, we will ship such of your FBS Products that we determine to be eligible (at our sole discretion), to addresses within countries we determine to be eligible for foreign shipments (at our sole discretion), subject to any additional terms on foreign shipments. In such a case, and subject to such additional terms implemented by Vendlor, the Seller or the Seller&#x2019;s customer shall bear the full cost of delivery and shall be listed as the importer and/or exporter of record, as applicable, on all Cross Border FBS, returns, and other shipments of Products and we shall not be listed as the importer or exporter on any import, export or other customs documentation. If Vendlor is listed on any import/export documentation, Vendlor reserves the right to refuse to ship the FBS Products covered by the import/export documents and any costs assessed against or incurred by Vendlor will be collected from you in accordance with the Site Terms (including by way of deduction from amounts payable to you), or by other method at our election.</li>
      </ol>
      <ol start="5">
      <li><strong>FBS SERVICES: </strong>During the <strong>FBS Term</strong> (being the period during which Vendlor provides the FBS Services in each Elected Country), Vendlor shall provide Seller the FBS Services in respect of certain Products in the relevant Elected Country designated by the Seller the &#x201C;<strong>FBS Products</strong>&#x201D;. The Seller can allocate any Products that it sells according to the Site Terms as FBS Products (provided such FBS Products weigh, when fully packaged, no more than the amount set out on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a> for each Elected Country and subject to any specific capacity limitations set out on the Site (whether generally or by Elected Country, and in each case as may be amended from time to time). At all times, Vendlor may refuse to provide the FBS Services in respect of any such Product(s). Seller may, at any time, withdraw any FBS Products from the scope of these FBS Terms.</li>
      </ol>
      <ol start="6">
      <li><strong>STORAGE SERVICES: </strong>We will provide storage services as described in these FBS Terms in the relevant Elected Country once we confirm receipt of delivery of such FBS Products in accordance with these FBS Terms. We will keep electronic records that track inventory of FBS Products by identifying the number of FBS Products stored in any fulfillment center. We will not be required to physically mark or segregate FBS Products from other inventory units (e.g., products with the same Vendlor standard identification number) owned by us, our Affiliates or third parties in the applicable fulfillment center(s). If we elect to commingle FBS Products with such other inventory units, both parties agree that our records will be sufficient to identify which products are FBS Products. We may move FBS Products among facilities. If there is a loss of or damage to any FBS Products while they are being stored, we will, as your sole remedy, reimburse you in accordance with our guidelines or protocols in force at that time, which may be referred to on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a> and you will, at our request, provide to us a valid tax invoice for the compensation paid to you. If we reimburse you for a FBS Product, we will be entitled to dispose of the FBS Product pursuant to paragraph 17 of these FBS Terms. This reimbursement is our total liability for any duties or obligations that we or our agents or representatives may have and is your only right or remedy.</li>
      <li><strong>FULFILLMENT SERVICES:</strong> As part of our Fulfillment Services, we will ship FBS Products from our inventory of your FBS Products to the shipping addresses in the Elected Country as included in valid customer orders. We may ship FBS Products together with products purchased from other merchants, including any of our Affiliate or may ship FBS Products separately that are included in a single customer order.</li>
      </ol>
      <ol start="7">
      <li><strong>FULFILLMENT SERVICES:</strong> As part of our Fulfillment Services, we will ship FBS Products from our inventory of your FBS Products to the shipping addresses in the Elected Country as included in valid customer orders. We may ship FBS Products together with products purchased from other merchants, including any of our Affiliate or may ship FBS Products separately that are included in a single customer order.</li>
      </ol>
      <ol start="8">
      <li><strong>ORDER </strong><strong>FULFILLMENT AND SHIPPING</strong>: In each Elected Country, to the extent that Products are to be shipped to the Seller&#x2019;s customer, Vendlor shall provide the relevant FBS Services upon the placement of the order through the Site (subject to the Seller&#x2019;s inventory of FBS Products being available to allow Vendlor to provide the FBS Services). The Seller retains full responsibility for ensuring that FBS Products are available to allow Vendlor to provide the FBS Services.</li>
      </ol>
      <ol start="9">
      <li><strong>FBS FEES: </strong>Subject to the payment of any Fees set out in the Site Terms generally for the provision of Services and the making available the Site for the purposes of selling Products, the FBS Services are currently provided without additional charge to Sellers. Vendlor retains the right to charge Sellers the FBS Fees for the FBS Services on the expiry of 30 days&#x2019; notice (<strong>FBS Fees Notice Period</strong>). The current indicative cost of each of the FBS Services is set out in on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a>. For the avoidance of doubt, the amount of the FBS Fees, and/or the scope of the FBS Services (or part of the FBS Services) for which they are chargeable is provided as an example of the likely charges for the provision of the FBS Services (or any part of them). Vendlor may update the amount or scope of the FBS Fees (or any part of them) at any time, for any Elected Country (either in whole or in part) (or for any other country).</li>
      </ol>
      <ol start="10">
      <li><strong>FBS FEES NOTICE</strong><strong> PERIOD: </strong>The FBS Fees Notice Period shall commence upon midnight on the date that the Site is updated to indicate the commencement of the FBS Fees Notice Period. The Seller shall not be liable to pay for FBS Fees for the FBS Services provided before the expiry of the FBS Fees Notice Period. Upon expiry of the FBS Fees Notice Period, the Seller shall pay Vendlor the FBS Fees for the FBS Services. The Seller acknowledges and expressly agrees that Vendlor may deduct the FBS Fees from the Seller&#x2019;s account in accordance with the Site Terms. The Seller acknowledges Vendlor can monitor all payment activities conducted through the Seller&#x2019;s account in accordance with the Site Terms.</li>
      </ol>
      <ol start="11">
      <li><strong>INDICATIVE FBS FEES: </strong>Subject to the expiry of the FBS Fees Notice Period, and to Vendlor&#x2019;s rights to change the FBS Fees, for each Elected Country including (but not limited to) as set out on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a>, Vendlor may charge and the Seller shall pay:
      <ul>
      <li><strong>the Fulfillment Fees</strong>, being the amount chargeable for each FBS Product that is sold and shipped through the Site, and which are chargeable according to the weight of the FBS Product and the Elected Country in which it is shipped (and subject in each case to the weight capacity limitations referred to on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a> and subject to any capacity limitations set out on the Site; and/or</li>
      <li><strong>the Storage Fees</strong>, being the amount chargeable for all FBS Products stored by Vendlor in a Vendlor fulfillment center facility (or on its behalf) based on the volume used per day. The volume of any Product shall be determined based on each relevant fully and properly packaged FBS Product when ready for shipment to customers. Vendlor (in its sole discretion) shall determine the volume of such Product for this purpose (based either on actual measurement or on measurement of a representative sample). The Storage Fees, in each Elected Country in which the FBS Products are stored shall be charged beginning on the day (up to midnight) that each FBS Product arrives at Vendlor fulfillment center, until, the earlier of the day (up to midnight) Vendlor:
      <ul>
      <li>receives an order for the Product to:
      <ul>
      <li>o be shipped to the Seller&#x2019;s customer;</li>
      <li>o be shipped to Seller&#x2019;s designated return location; or</li>
      </ul>
      </li>
      <li>disposes of such FBS Product(s) in accordance with these FBS Terms; and/or</li>
      </ul>
      </li>
      <li><strong>the Return Fee, </strong>being the amount chargeable for making available the Return Products for collection in accordance with paragraph 18 of these FBS Terms.</li>
      </ul>
      </li>
      </ol>
      <ol start="12">
      <li><strong>SHIPPING TO Vendlor (GENERAL): </strong>Seller is responsible for delivering the Products to the relevant Vendlor fulfillment center facility in the relevant Elected Country which shall be subject to inspection in accordance with these FBS Terms. Seller shall pay for all costs incurred to ship the Products to Vendlor (including costs of freight and transit insurance) and Vendlor shall not pay any shipping costs. Seller is responsible for payment of all customs, duties, taxes, and other charges. Seller shall not deliver to Vendlor, and Vendlor may refuse to accept, any Products or shipment that does not conform to the Site Terms or these FBS Terms. Vendlor&#x2019;s confirmed receipt of delivery does not: (a) indicate or imply that any Product has been delivered free of loss or damage, or that any loss or damage to any Product later discovered occurred after confirmed receipt of delivery&#x37E; (b) indicate or imply that Vendlor actually received the number of units of the Product(s) specified by the Seller&#x37E; (c) waive, limit, or reduce any of Vendlor&#x2019;s rights under these FBS Terms; or (d) confirm that such FBS Product(s) meets any necessary criteria (including as to the authenticity of the Product(s)), (e) confirm that such FBS Product(s) have not expired by reference to any expiry date or period applicable to the Products or (f) warrant, represent, affirm or contest the scope or validity of any intellectual property rights related to the Products. In addition, if you ship Products from outside the applicable Elected Country to fulfilment centres, you will list yourself as the importer/consignee and nominate a customs broker. If Vendlor is listed on any import documentation, Vendlor reserves the right to refuse to accept the FBS Products covered by the import documents and any costs assessed against or incurred by Vendlor will be collected from you in accordance with the Site Terms (including by way of deduction from amounts payable to you), or by other method at our election.</li>
      </ol>
      <ol start="13">
      <li><strong>SHIPPING TO Vendlor (DISCOUNT): </strong>Subject always to paragraph 12 of these FBS Terms, we may, at our option, allow you to ship the FBS Product(s) in the relevant Elected Country at your expense to fulfilment centres using discounted shipping rates that we may make available to you for certain carriers. In such event, you will use the processes and supply the information that we require for you to obtain such discounted rates. You also must comply with standard operating procedures, weight and size restrictions, and other shipping requirements of the applicable carriers. If we provide you with the estimated shipping costs prior to shipment, you acknowledge and agree that actual shipping costs may vary from such estimates. In addition, if the weight of the FBS Product(s), as determined by the applicable carrier, differs from that submitted by you to us for purposes of determining the estimated shipping costs, then: (a) you may be charged more than the estimated shipping costs if the carrier determines that such FBS Product(s) weigh(s) more than as submitted by you&#x37E; or (b) you may be charged the full amount of the estimated shipping costs even if the carrier determines the weight to be less than that submitted by you. You will not use carrier account information (e.g., carrier account number, amount of shipping rates, etc.) for any purpose, nor disclose such information to any third party, and you will protect such information as Vendlor&#x2019;s confidential information in accordance with Site Terms. As between you, us, and the applicable carrier, you will be the shipper of record, and we will make payment to the carrier with respect to the shipment of all applicable FBS Product(s) using such discounted rates. Title and risk of loss for any such FBS Product(s) shipped using discounted rates provided by us under this paragraph of these FBS Terms will remain with you, and our provision of such shipping rates will not create any liability or responsibility for us with respect to any delay, damage, or loss incurred during shipment. You authorize the applicable carrier to provide us with all shipment tracking information.</li>
      </ol>
      <ol start="14">
      <li><strong>SHIPPING AND GIFT WRAP:</strong> For any FBS Products, where relevant, we will determine the amounts charged to the customer for shipping and gift wrap services (if any) for the FBS Products that we fulfil as part of the FBS Services in the relevant Elected Country. As between you and us, these charges will be your charges to the customer, and we will report them to you. We will charge you (and you will pay us) a fee equal to the amount of such charges to the customer. In the case of shipments of FBS Products sold through the Site that qualify for the &#x201C;Free Shipping&#x201D; promotion, the amounts charged to the customer for shipping any such FBS Products that Vendlor fulfils will first be charged to the customer and will next be deducted from the total charges to the customer as your promotion and Vendlor will not charge you the fee described above. If you ship FBS Products to us using the shipping rates that we may make available pursuant to these FBS Terms, you will reimburse us for the actual amounts charged to us by the applicable carrier for such shipments.</li>
      </ol>
      <ol start="15">
      <li><strong>INSPECTION:</strong> Upon receipt at or delivery to a Vendlor fulfillment center facility (whether for the first time or following a return from the Seller&#x2019;s intended customer) of a FBS Product(s), the Seller acknowledges and agrees that, at Vendlor&#x2019;s discretion, any such FBS Product(s) shall be subject to a quality inspection by Vendlor (or on its behalf). To the extent that the packaging of such FBS Product(s) is opened or removed, and the FBS Product(s) passes the inspection, Vendlor agrees that the FBS Product(s) shall be repacked or resealed in such a manner as to be suitable for sale to customers. Vendlor retains the right in its sole discretion to refuse to accept the FBS Products or refuse to provide the FBS Services in respect of any such FBS Product(s) that Vendlor determines: (a) is defective, damaged, unfit for a particular purpose, or lacking required label(s)&#x37E; (b) the labels for which were not properly registered with Vendlor before shipment or does not match the Product that was registered by the Seller&#x37E; (c) is otherwise an excluded Product (in accordance with the Site Terms) or does not comply with the Site Terms&#x37E; (d) is unsellable, or cannot be fully and properly repaired by or for us to a suitable condition for resale (including where the expiry dates have passed, or where the remaining period prior to expiry date is less than fifty percent (50%) of the total shelf life of that Product)&#x37E; or (e) is otherwise unsuitable, and together such FBS Products as set out in (a) to (e) shall be called &#x201C;<strong>Failed Inspection Products</strong>&#x201D;.</li>
      </ol>
      <ol start="16">
      <li><strong>UNSOLD ITEMS: </strong>To the extent that Products stored at a Vendlor fulfillment center facility are not sold within sixty calendar days from the date of their receipt at a Vendlor fulfillment center facility (&#x201C;<strong>Unsold Items</strong>&#x201D;), such Products must be collected by the Seller. Vendlor may offer the Seller transportation/shipment facilities to remove the items from Vendlor&#x2019;s fulfillment center facility at its standard price. If you do not respond to a request to collect an Unsold Item, or do not collect an Unsold Items, we shall deem it to be an &#x201C;<strong>Uncollected Unsold Item</strong>&#x201D;.</li>
      </ol>
      <ol start="17">
      <li><strong>RETURNS TO Vendlor AND RE-LISTING</strong><strong>: </strong>Vendlor shall allow the Seller&#x2019;s customer to return any FBS Products according to the Site Terms provided that such FBS Products were shipped to addresses within the same Elected Country in accordance with the terms of these FBS Terms. Following their return, if the FBS Products are in a condition that may allow the FBS Products to be resold through the Site (to be determined by Vendlor at its discretion) and have been returned in accordance with these FBS Terms, then Vendlor agrees to re-list such Products for sale according to these FBS Terms in the same Elected Country (but not according to any other terms or by reference to any other service that Vendlor (or its affiliates) may offer). Except as provided in paragraph 20, you will retain or retake title of all FBS Products that are returned by customers.</li>
      </ol>
      <ol start="18">
      <li><strong>RETURNS TO YOU: </strong>You may, at any time, request that FBS Products be returned to you or that we dispose of FBS Products. We may (i) make available for collection those FBS Products that you have requested to be returned to you, or (ii) return: (a) FBS Products to you (for any reason), (b) Failed Inspection Products or (c) Unsold Items, including (in each of (i) and (ii)) upon termination of these FBS Terms (<strong>Return Products</strong>) and we shall charge you the Return Fees for the return of each such Return Product. The Return Products will be sent to your designated shipping address. However, if (a) the designated shipping address we have for you is outdated or incorrect, (b) you have not provided a designated shipping address in the Elected Country, or (c) we cannot make arrangements for you to pay for the return shipment, then the FBS Product(s) will be deemed abandoned and we, to the extent permitted by Applicable Laws in the Elected Country, may elect to dispose of them in our sole discretion in accordance with paragraph 20 of these FBS Terms.</li>
      </ol>
      <ol start="19">
      <li><strong>FBS PRODUCT RECALLS:</strong> You will promptly notify us of any recalls or potential recalls, of any FBS Products and cooperate and assist us in connection with any such recalls, including initiating the procedures for Return Products. In addition, to the Return Fees, you will be responsible for all costs and expenses you, we or any of our or your affiliates incur in connection with any recall or potential recall of any FBS Products (including the costs to return, store, repair, liquidate, or deliver to you or any vendor any of these Products).</li>
      </ol>
      <ol start="20">
      <li><strong>DISPOSAL OF RETURN PRODUCTS:</strong> We, if we so elect, may dispose of any Return Products or Uncollected Unsold Items (and you will be deemed to have consented to our action): (i) immediately if we determine in our sole discretion that such FBS Product creates a health, safety, or liability risk to Vendlor, our personnel, or any third party&#x37E; (ii) if you fail to direct us to return or dispose of any such FBS Product within thirty (30) days after we notify you that such FBS Product has been recalled&#x37E; or (iii) if you fail to direct us to return or dispose of any such FBS Product within thirty days (or as otherwise specified on the Site) after we notify you. We may dispose of any such FBS Products in the manner we prefer. Title to each such disposed FBS Product(s) will transfer to us at no cost, as necessary for us to dispose of the FBS Product(s), and we will retain all proceeds, if any, received from the disposal. You will reimburse us for all costs and expenses we incur in connection with the storage, and return or disposal of any such FBS Products.</li>
      </ol>
      <ol start="21">
      <li><strong>CUSTOMER SERVICE</strong>: We will be responsible for and have sole discretion regarding all customer service issues relating to packaging, handling and shipment, and customer returns, refunds, and adjustments related to FBS Products. We will have the right to determine whether a customer will receive a refund, adjustment or replacement for any FBS Products. In situations relating to FBS Products where the wrong FBS Product(s) was delivered or the FBS Product(s) was damaged or lost or is missing, unless we determine that the basis for such request is caused by you or any of your employees, agents, or contractors, we will, as your sole and exclusive remedy and at our option for any such FBS Products: (i) ship a replacement unit of the FBS Product(s) to the customer and reimburse you in accordance with our guidelines or protocols in force at that time, (including (but without limitation) to those referred to on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a> for the replacement FBS Product(s), or (ii) process a refund to the customer and reimburse you in accordance with our guidelines or protocols in force at that time, including (but without limitation) to those referred to on the Site at <a href="http://help.sell.Vendlor.com/en/knowledge-base/what-does-the-fulfilled-by-Vendlor-fee-structure-look-like/">http://help.sell.Vendlor.com/en/article-categories/fulfillment-by-Vendlor-com/</a><u>)</u> for the FBS Product(s). If, in these circumstances, we provide a replacement FBS Product(s) or refund to a customer and that customer returns the original FBS Product(s) to us, we will be entitled to dispose of the original FBS Product(s) pursuant to paragraph 19 of these FBS Terms. Any replacement FBS Product(s) shipped by us under these FBS Terms will be deemed to be, and will be treated in the same manner as, an order and sale of such FBS Product(s) from you to the customer via the applicable Site using the applicable Service in accordance with, and subject to these FBS Terms and the Site Terms.</li>
      </ol>
      <ol start="22">
      <li><strong>TAX</strong><strong>: </strong>Seller acknowledges that it or its agent is solely responsible for identifying and resolving any sales, customs and use tax collection issues for product orders, including the necessity of charging and collecting such taxes. Seller understands and acknowledges that storing Products at fulfilment centres may create a tax nexus for Seller in any Elected Country or other country, state, province, emirate, or other localities in which FBS Products are stored, and Seller will be solely responsible for any taxes owed as a result of such storage. If any taxes are assessed against Vendlor as a result of performing the FBS Services for the Seller, Seller shall be responsible for such taxes and Seller shall indemnify and hold Vendlor harmless from such taxes. All FBS Fees are exclusive of applicable taxes and duties, including, without limitation, VAT, sales and other similar transaction taxes, excise taxes and gross receipt taxes (&#x201C;<strong>Indirect Taxes</strong>&#x201D;). If the FBS Fees payable by Seller are subject to Indirect Taxes, then Indirect Taxes will be charged by Vendlor in addition to the FBS Fees payable under these FBS Terms. Seller will provide such information to Vendlor as reasonably required to determine whether Vendlor is obligated to collect Indirect Taxes from Seller or to allow Vendlor to comply with its legal obligations in relation to the correct collection and enforcement of Indirect Taxes.</li>
      </ol>
      <ol start="23">
      <li><strong>INDEMNITY: </strong>In addition to your obligations under the Site Terms, you agree to indemnify, defend, and hold harmless us, our affiliates, and our and their respective officers, directors, employees, representatives, and agents against any Claim that arises from or relates to: (a) the FBS Product(s) (whether or not title has transferred to us, and including any FBS Product(s) that we identify as yours), including any personal injury, death, or property damage&#x37E; (b) the shipment, export, or delivery of your Products to addresses outside of the Elected Country in accordance with paragraph 4 of these FBS Terms (including with respect to any classification data and other information provided by you to us in connection therewith, and notwithstanding any rights we have under paragraph 4 of these FBS Terms or any certifications we may make in connection with the shipment, export, or delivery of your FBS Products)&#x37E; (c) any of your taxes or the collection, payment, or failure to collect or pay your taxes&#x37E; and, if applicable (d) any sales, use, value added, personal property, gross receipts, excise, franchise, business, or other taxes or fees, or any customs, duties, or similar assessments (including penalties, fines, or interest on any of the foregoing) imposed by any government or other taxing authority in connection with the shipment of the FBS Product(s) outside of the Elected Country in accordance with paragraph 4 of these FBS Terms (collectively, &#x201C;<strong>Foreign Shipment Taxes</strong>&#x201C;).</li>
      </ol>
      <ol start="24">
      <li><strong>RELEASE:</strong> You, on behalf of yourself and any successors, subsidiaries, affiliates, officers, directors, shareholders, employees, assigns, and any other person or entity claiming by, through, under, or in concert with them (collectively, the &#x201C;<strong>Releasing Parties</strong>&#x201C;), irrevocably acknowledge full and complete satisfaction of and unconditionally and irrevocably release and forever fully discharge Vendlor and each of our affiliates, and any and all of our and their predecessors, successors, and affiliates, past and present, as well as each of our and their partners, officers, directors, shareholders, agents, employees, representatives, attorneys, and assigns, past and present, and each of them and all Persons acting by, through, under, or in concert with any of them (collectively, the <strong>&#x201C;</strong><strong>Released Parties</strong><strong>&#x201C;</strong>), from any and all claims, obligations, demands, causes of action, suits, damages, losses, debts, or rights of any kind or nature, whether known or unknown, suspected or unsuspected, absolute or contingent, accrued or unaccrued, determined or speculative (collectively, &#x201C;<strong>Losses</strong>&#x201C;) which the Releasing Parties now own or hold or at any time have owned or held or in the future may hold or own against the Released Parties, or any of them, arising out of, resulting from, or in any way related to the shipment, export, or delivery of FBS Products to addresses outside of the Elected Country in accordance with paragraph 4 of these FBS Terms, including any tax registration or collection obligations. You, on behalf of yourself and all other Releasing Parties, recognize that you, and each of them, may have some Losses, whether in tort, product liability, contract, warranty, or otherwise, against the Released Parties of which you, or any of them, are totally unaware and unsuspecting, or which may arise or accrue after the date you register for or use FBS Services, which the Releasing Parties are giving up by agreeing to these FBS Terms. It is your intention in agreeing to these FBS Terms that these FBS Terms will deprive the Releasing Parties of each and all such Losses and prevent the Releasing Party from asserting any such Losses against the Released Parties, or any of them.</li>
      </ol>
      <ol start="25">
      <li><strong>ADDITIONAL REPRESENTATION </strong>In addition to your representations and warranties in section 6 of the Site Terms, you represent and warrant to us that: (a) you have valid legal title to all FBS Products and all necessary rights to distribute the FBS Products and to perform under these FBS Terms&#x37E; (b) you will deliver all the FBS Products to us in new condition (or in such condition otherwise described by you in the applicable Product listing) and in a merchantable condition&#x37E; (c) all the FBS Products and their packaging will comply with all applicable marking, labelling, and other requirements required by Law&#x37E; (d) no Unit is or will be produced or manufactured, in whole or in part, by child labour or by convict or forced labour&#x37E; (e) you and all of your subcontractors, agents, and suppliers involved in producing or delivering FBS Products will strictly adhere to all Applicable Laws of the Elected Country, its territories, and all other countries where Units are produced or delivered, regarding the operation of their facilities and their business and labour practices, including working conditions, wages, hours, and minimum ages of workers&#x37E; and (f) that all FBS Product(s) that may be shipped outside of the Elected Country in accordance with paragraph 4 of these FBS Terms: (i) can be lawfully exported from the United Arab Emirates, without any license or other authorization&#x37E; and (ii) can be lawfully imported into, and comply with all Applicable Laws of, any eligible country.</li>
      </ol>
      <ol start="26">
      <li><strong>SUBCONTRACTORS</strong><strong>:</strong>Vendlor reserves the right to subcontract with other individuals and businesses for FBS Services required to be performed pursuant to these FBS Terms.</li>
      </ol>
      <ol start="27">
      <li><strong>EFFECT OF TERMINATION: </strong>Following any termination of these FBS Terms (whether in whole or in part), Vendlor shall, as directed by Seller, return to you or dispose of the FBS Products held subject to these FBS Terms. Upon any termination of these FBS Terms, all rights and obligations of the Parties under these FBS Terms, except that the rights and obligations of the Parties with respect to FBS Products received or stored by Vendlor as of the date of termination will survive the termination. To the extent relevant, Seller shall immediately return to Vendlor all property (including without limitation, Confidential Information and all material related to any customers) that it has received from Vendlor in connection with the performance of its obligations.</li>
      </ol>
      <ol start="28">
      <li><strong>INSURANCE</strong>: During the FBS Term, Vendlor recommends that the Seller maintains with a financially sound insurance company an insurance policy or policies insuring the Seller against potential liabilities under or in relation to the receipt of the FBS Services (including in respect of product Liability and bodily Injury, including death and property damage) for each Elected Country in which the FBS Services are provided and to an extent and to limits that would be reasonably expected under the standards of good industry practice and Applicable Laws in the Elected Country.</li>
      </ol>
      </div>
    </Container>
  )
}